### ISSUE TITLE
V2: A completely new version of enkanetwork.js

### ISSUE THREAD

**Issue by Almighty-Shogun** [Jelosus2/enkanetwork.js#2]
Hello everyone,

Together with @Jelosus2 I am making a new version of this package. There will be some (major) changes in the package that will benefit us and you users of this package as well. In this issue I will explain what we have planned and why.

# What will be changed?
As of now all the data regarding `characters`, `weapons`, `artifacts` etc is stored in the package itself. Because we have to update the package each time there is a new version, this can be annoyed for some users. Therefore we are rewriting the package to get the data from one place. Let's explain how it works (in this example is based on a character).

# How does it work?
~~When you want to get data from a character you have to search on their ID in this case we will use Nahida's ID (**10000073**). When you want to get the data of Nahida it will make a request to `https://enka.jelosus1.eu/data/characters/10000073.json`. It will work like this with every data type. It will go as following: `https://enka.jelosus1.eu/data/<DATA_TYPE>/<ID>.json`. Since all the data is stored seperately instead of all being mashed into one big file it should be faster with getting the data as well. The JSON files on the website will be updated as soon as possible when the new data is available for us.~~

# Why is this coming?
Simply said. It will reduce the times the package has to be updated for each version content and if there is anything wrong with the data we can apply the changes without having to publish a new update.

# What is on the plannig?
- [x] Make a new script to generate the JSON files
- [x] ~~Storing all the JSON files on the webhost~~
- [x] Reduce the amount of files in the package
- [ ] Making documentation
- [ ] Making API
  - [x] player
  - [x] player-character
  - [ ] profile
  - [ ] profile builds
- [ ] Implementing the new version in the `dev` branch
- [x] Implementing cache system ~~(ask @Jelosus2 about this)~~

# When will this be done?
As of now I have no idea how quickly this can be achieved. But our aiming goal is to get it completed before the v3.3 version update.

# User input
I would like to hear from you users what we can do to make this package even better. Are we missing some features? Is something working slow? Is something that needs to be improved? Is something not working? Those kinda questions are popping into my head when thinking about this subjects. So please adress anything that you have and we will look into it.

**Comment by ChrisSch-dev** [comment]
how do you plan on making this Cache system?

**Comment by Almighty-Shogun** [comment]
> how do you plan on making this Cache system?

You will have to ask @Jelosus2 for that. He is the one that came with the idea

**Comment by Jelosus2** [comment]
> how do you plan on making this Cache system?

We will use a library to store and retrieve the cached data

**Comment by Almighty-Shogun** [comment]
> how do you plan on making this Cache system?

The cache has been moved to the API that get's the data. The cache system will work on the ttl provided by enka.network.

**Comment by Almighty-Shogun** [comment]
We have decided to make an API wrapper for this package (instead of loading a lot of JSON files) it will be added to the package as quickly as possible. I am currently sick at the moment, but I am working as hard as I can to implement it before 3.3 releases
