### ISSUE TITLE
Delete corrupt cache files immediately

### ISSUE THREAD

**Issue by RadEagle** [Jelosus2/enkanetwork.js#4]
Here's the error I ran to when I try to retrieve the cached file. I believe this happened because my program retrieved the file too many times.

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at CacheHandler.get (/home/runner/GenshinBot/node_modules/enkanetwork.js/dist/handlers/CacheHandler.js:57:27)
    at Wrapper.getPlayer (/home/runner/GenshinBot/node_modules/enkanetwork.js/dist/client/Wrapper.js:72:36)...

If possible, can you immediately delete the cached file and then cache the newly fetched enka-json data?

**Comment by Jelosus2** [comment]
Yes, it has been added to the new version of the package, thank you for your report.

**Comment by RadEagle** [comment]
Thanks! Now with the new update, I've noticed that it takes a rather long time to fetch data from enka.network in general. Both with and without the cache. Is it something that fixes itself as time passes or would there be something you can investigate?

**Comment by Jelosus2** [comment]
yes, i think i know why is that, working on it right now, will bring a new update as soon as i fix it!

**Comment by Jelosus2** [comment]
@RadEagle fixed in the new version

**Comment by RadEagle** [comment]
Thank you again for fixing it promptly! I'll close this issue now since I see no further problems.
