### ISSUE TITLE
How do I determine the artifacts rolledSubstatsIds value

### ISSUE THREAD

**Issue by jsdawn** [Jelosus2/enkanetwork.js#5]

**Comment by jsdawn** [comment]
ex: 
```js
rolledSubstatsIds:[
  501081, 501064, 501223
]
```

**Comment by Jelosus2** [comment]
Hey! To get the values of the substats rolled in an artifact you can use the excel named `ReliquaryAffixExcelConfigData`, it can be found [here](https://gitlab.com/Dimbreath/AnimeGameData/-/blob/master/ExcelBinOutput/ReliquaryAffixExcelConfigData.json). You can filter by the id and get the value using the `propValue` key. In the next version of the package i will implement a method to make this process more easier, thanks for your feedback!

**Comment by Jelosus2** [comment]
Since there was no reply for a long time i'll close the issue, but feel free to open another or reopen this one if you still have questions.
