### ISSUE TITLE
Confusion between skillsExtraLevel key & skills id

### ISSUE THREAD

**Issue by HoraceHuang-ui** [Jelosus2/enkanetwork.js#6]
The 3rd & 5th constellations can add Elemental Burst & Elemental Skill levels by 3, but in the example below, the given key in `skillsExtraLevel` is not respective to the `id` in `skills.elementalBurst`:

![image](https://github.com/Jelosus2/enkanetwork.js/assets/67905897/59e146ef-a120-429d-930e-04b88d6e162a)

which leads to some confusion.

I wonder if it's made by design?

**Comment by Jelosus2** [comment]
Hi, sorry for the late reply. Each skill id has a field named `proudSkillGroupId`, which is the key of the skillsExtraLevel object. You can fetch those with the excel named **AvatarSkillExcelConfigData.json**, you can download it [here](https://gitlab.com/Dimbreath/AnimeGameData/-/blob/master/ExcelBinOutput/AvatarSkillExcelConfigData.json?ref_type=heads). Then you can filter by the skill id and check the proudSkillGroupId field. Hope this works for you!
![image](https://github.com/Jelosus2/enkanetwork.js/assets/75176441/d191fe5a-c75b-49a1-8e99-5bb93142a054)

**Comment by HoraceHuang-ui** [comment]
That explains all. Thanks!
